### PR TITLE
Use 'localhost' when running chrome locally

### LINKED ISSUE #2164: Headless chrome tests fail on systems where hostname doesn't actually resolve
The code in `spec/chrome-fractal-tester.js` assumes that the host system's hostname is something that can actually be resolved. This is the case most of the time, but apparently not all the time--on @maya's system, it results in a `net::ERR_NAME_NOT_RESOLVED` from headless chrome.

I am strongly suspecting this has something to do with JAMF.

Anyways, the reason I used the hostname instead of just `localhost` was because of Docker and other situations where Chrome may not be running on the same logical host.  This should be fixable if, say, we only use the system's hostname when `REMOTE_CHROME_URL ` is also set, and use `localhost` otherwise.

### PR DESCRIPTION
**Pull request by toolness**
Fixes #2164.

### CODE REVIEW

**Comment by toolness** [comment]
@maya can you run this on your system and make sure that `npm run spec` works ok?

**Comment by maya** [comment]
@toolness no, it's not working for me.

**Comment by toolness** [comment]
Hmm, does it still give the same error it gives without this PR?

**Comment by maya** [comment]
Here's the error, but I don't know if it was the same as the one we got before:
```
➜  web-design-standards git:(revert-headers) ✗ npm run spec

> uswds@1.4.0 spec /Users/mayaben-ari/Code/web-design-standards
> npm run mocha -- 'spec/**/*.spec.js'


> uswds@1.4.0 mocha /Users/mayaben-ari/Code/web-design-standards
> mocha --opts spec/mocha.opts "spec/**/*.spec.js"

/Users/mayaben-ari/Code/web-design-standards/spec/chrome-fractal-tester.js:9
const HOSTNAME = REMOTE_CHROME_URL ? os.hostname().toLowerCase()
                 ^

ReferenceError: REMOTE_CHROME_URL is not defined
    at Object.<anonymous> (/Users/mayaben-ari/Code/web-design-standards/spec/chrome-fractal-tester.js:9:18)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/mayaben-ari/Code/web-design-standards/spec/headless-chrome.spec.js:5:29)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at /Users/mayaben-ari/Code/web-design-standards/node_modules/mocha/lib/mocha.js:230:27
    at Array.forEach (native)
    at Mocha.loadFiles (/Users/mayaben-ari/Code/web-design-standards/node_modules/mocha/lib/mocha.js:227:14)
    at Mocha.run (/Users/mayaben-ari/Code/web-design-standards/node_modules/mocha/lib/mocha.js:495:10)
    at Object.<anonymous> (/Users/mayaben-ari/Code/web-design-standards/node_modules/mocha/bin/_mocha:469:18)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Function.Module.runMain (module.js:605:10)
    at startup (bootstrap_node.js:158:16)
    at bootstrap_node.js:575:3
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! uswds@1.4.0 mocha: `mocha --opts spec/mocha.opts "spec/**/*.spec.js"`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the uswds@1.4.0 mocha script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/mayaben-ari/.npm/_logs/2017-10-05T23_36_26_008Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! uswds@1.4.0 spec: `npm run mocha -- 'spec/**/*.spec.js'`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the uswds@1.4.0 spec script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/mayaben-ari/.npm/_logs/2017-10-05T23_36_26_028Z-debug.log
```

**Comment by maya** [comment]
Checked again and it's working 👍

**Comment by toolness** [comment]
Woot thanks!

**Pull request merged**
