### PR TITLE
Fix accessibility citation

### LINKED ISSUE #823: Playbook - incorrect citation on accessibility
@ https://playbook.cio.gov/designstandards/getting-started/

"All of the designs meet the WCAG 2.0 AA accessibility guidelines and are compliant with Section 508 of the Americans with Disabilities Act. If you choose to customize them, ensure they continue to meet the requirements listed in the “Accessibility” section of each design."

One Correction - the correct reference is Section 508 of the Rehabilitation Act of 1973. Section 508 is not a section of the American's with Disabilities Act.

### PR DESCRIPTION
**Pull request by maya**
This fixes the reference to Section 508 on the Getting Started page, so it reads "Section 508 of the Rehabilitation Act of 1973."

Resolves #823.

### CODE REVIEW

**Comment by fureigh** [comment]
@maya: Feel free to kick that last commit out if it's overkill. Just went to http://www.section508.gov/content/learn to doublecheck and noticed that the year information is longer than just 1973, so I changed it to read "Section 508 of the Rehabilitation Act of 1973, as amended in 1998 (29 U.S.C. § 794 (d))."

**Comment by brittag** [comment]
I'd suggest saying "Section 508 of the Rehabilitation Act of 1973, as amended in 1998." It looks like [the 1998 amendment added these accessibility requirements](http://www.section508.gov/content/learn/laws-and-policies), so that's nice to mention, but likely we don't need the specific reference to the section of the law. :)

**Comment by maya** [comment]
Updated to the briefer "Section 508 of the Rehabilitation Act" via https://github.com/18F/web-design-standards/issues/823#issuecomment-148146492.

**Comment by fureigh** [comment]
:+1: Merging...

**Pull request merged**
