### PR TITLE
Reorganizing repository file/folder structure

### LINKED ISSUE #974: Updating structure for the web-design-standards Github repository
## User Story 
https://trello.com/c/jPnKDPnl/36-as-a-developer-on-the-wds-i-want-to-be-able-to-clearly-understand-the-file-structure-of-the-wds-repo-at-a-glance

## Acceptance Criteria

- [ ] History of the original repo should be maintained and not lost.
- [ ] The maintenance between the public-facing website and the developer-focused package should be easily done without having to sync or copy files between the two

### PR DESCRIPTION
**Pull request by juliaelman**
The work in this pull request reorganizes the files and folders to help assist with automation of the project. A few things to note:

- The Draft WDS website pages now live in the `/docs` folder.
- `_config.yml` has a new variable called `version` for us to be able to update the release version around the site more efficiently.
- The `Gemfile` now includes the the `web_design_standards_gem` instead of relating the the actual files in the repo: 

Fixes #974

### CODE REVIEW

**Comment by rogeruiz** [comment]
This looks great. We should document the new Jekyll development process in the README. I'm not quite sure, based on the documentation in the `readme`, how these changes affect building the website locally. Could you update that in the `readme`?

**Comment by juliaelman** [comment]
@rogeruiz thanks for your review! There should not be any changes to the `README.md` installation/local usage workflow, as we now have the `source` pointing to the `/docs` folder. See here: https://github.com/18F/web-design-standards/pull/978/files#diff-aeb42283af8ef8e9da40ededd3ae2ab2R7

Did some testing, but let me know if you have any specific errors or issues you are seeing as you build locally! :rocket:

**Comment by juliaelman** [comment]
@rogeruiz taking a second look and while the build is the same, there are some docs that DID need updating in response to where to find all the things! Those should be updated now.

**Comment by rogeruiz** [comment]
Seeing some strange errors on the build for this PR.

https://travis-ci.org/18F/web-design-standards/builds/106562512#L174-L184

I'm going to attempt to rebuild this, but the new documentation looks good to me. I think it makes more sense to split the repository up into two silos with `source`, `dist`, and `docs` living at the root directory along with the necessary `config` and `dotfiles` within this PR. I'm comfortable merging this in once the `source` directory is created and pushed up.

**Comment by maya** [comment]
@rogeruiz would it be `source` or `src`?

**Comment by msecret** [comment]
I say `src`

**Comment by juliaelman** [comment]
@rogeruiz thanks for the feedback! The build is now fixed after updating the `.travis.yml` to remove the build via the `./go` script. @mbland is working on a solve here >> https://github.com/18F/go_script/issues/16

I've also updated the repo to only hold a `src/` directory, as I see the `dist/` directory coming into play once your gulpification of the repo is in place.

**Comment by rogeruiz** [comment]
Looks good to me :+1: :rocket: :guitar: :dancer:

**Pull request merged**
