### PR TITLE
Footer h4 semantics

### PR DESCRIPTION
**Pull request by madmanlear**
Link lists in the big footer included an h4 as a direct child of a ul, and this is not allowed.

- Wrapped footer h4 in li to comply with semantics
- Updated styles to suit

Resolves issue #794

### CODE REVIEW

**Comment by msecret** [comment]
Hi @madmanlear thanks for the PR! First off, could you run the build process and commit some of the compiled files? It should just be `npm install && npm run build`. I think these files should have changes and should be checked in:

```sh
        modified:   dist/css/uswds.css
        modified:   dist/css/uswds.min.css
        modified:   dist/css/uswds.min.css.map
```

Second, the first `<li>` now needs a little bit of bottom margin to stay consistent with what's current on the site. I think this is due from it changing from an `<h>` to a `<li>`. You can see the difference if you compare the space between "Topic"'s and "Secondary link"'s on your branch vs https://standards.usa.gov/footers. I took a look and I think it needs this:

```scss
.usa-footer-primary-link {
   margin-bottom: .8rem;
}
```

Besides those two things, this is looking good for a merge.

**Comment by madmanlear** [comment]
Hey @msecret thanks for your feedback! You'll find these changes in the latest commit.

**Comment by msecret** [comment]
This looks good for me, @maya wanna take a look? Also, @madmanlear there are merge conflicts now probably because of other things I've been merging in this afternoon. You'll likely have to rebase and run the build again when you get merge conflicts. I can also open up another branch and do that for you if it helps, I'm very used to it by now.

**Comment by madmanlear** [comment]
@msecret I _think_ I did it correctly but if not I'd love a breakdown of the process you use. Thanks!

**Comment by msecret** [comment]
@madmanlear it depends on what you named the upstream remote, in this case the 18F/web-design-standards remote. If you named it `upstream`, and your own fork `origin`:

```
git checkout 18f-pages-staging
git fetch upstream
git rebase upstream/18f-pages-staging
git checkout footer-h4-semantics
git rebase 18f-pages-staging
## merge conflict!
npm run build
git add .
git rebase --continue
## if another merge conflict, repeat last 3 steps
git push -f origin footer-h4-semantics
```

**Comment by maya** [comment]
@msecret I'd personally prefer if we left h4's margin/padding as is and remove the li padding it's within. It will be more consistent with our type system.

**Comment by madmanlear** [comment]
@maya That makes perfect sense, but even after removing all top spacing from the li, the h4's top margin is still t00 much space compared to staging.

Here's the difference, with staging on the left:

screen shot 2016-05-11 at 5 21 47 pm

I could instead increase the css specificity so that necessary changes to the h4 only get applied as a child of .usa-footer-primary-link

Additionally, having top margin on the immediate child of the li means that the li's layout doesn't start until the top of the h4, creating a situation where the background arrow on the li can't be placed vertically at the center. The above image shows background-position-top at 0.4rem to compensate. Here it is with background-position-top at center:

screen shot 2016-05-11 at 5 28 21 pm

Let me know if you'd like me to commit any of this to see what I mean in code.

**Comment by juliaelman** [comment]
@madmanlear thank you again for your contribution! We've made some updates recently and it looks like  we are needing you to do another rebase. Please let us know if you need any help. We really appreciate your contribution to the Standards!

**Comment by madmanlear** [comment]
@juliaelman Hi, no problem, I thought I was awaiting feedback from @maya. It should be up to date now!

**Comment by maya** [comment]
@madmanlear for some reason, I just checked and this branch looks like it's missing the accordion links on mobile:

screen shot 2016-05-18 at 12 20 35 pm

And it also looks misaligned:
screen shot 2016-05-18 at 12 20 43 pm

I have not been able to check on the your previous responses bc of the above.

**Comment by madmanlear** [comment]
@maya Sorry about those issues! I can't replicate on my end, but I've rebased again to make sure my branch is up to date with staging. Let me know if the issue persists!

**Comment by maya** [comment]
@madmanlear the rebase fixed it, thanks!

**Comment by maya** [comment]
@madmanlear sorry for the trouble again, it's hard to review bc of the 361 files changed now. I think if this was rebased, we shouldn't show the 361. Would you be able to do that? Or resubmit it if that easier?

**Comment by madmanlear** [comment]
@msecret Could you provide some guidance on this issue? I rebased as instructed, but if that is causing the issue @maya is having (and I see it too) then I can revert or make a new PR so she can review just what's changed.

**Comment by msecret** [comment]
@madmanlear I'll guide you through what I did to clear up these conflicts, and hopefully that will work.

```
git checkout 18f-pages-staging
git fetch upstream
git rebase upstream/18f-pages-staging
git checkout footer-h4-semantics
git rebase 18f-pages-staging
# You'll get merge conflicts here, likely about certain files being deleted
git status
# Check the status, this will show you what files are in conflict, likely about files in the dist directory
git rm -rf  dist
# You might want to check status again here and make sure all files are "added", or are green.
git rebase --continue
# At this point, you may or may not get more merge conflicts. If you do, try git rm and rebase continue in exact same way as above.
```

Let me know if this works. You should ideally have only a few files changed in the src/stylesheets dir.

**Comment by rogeruiz** [comment]
@madmanlear Adding to what @msecret posted above ☝️

I did a local rebase from your branch on `madmanlear/footer-h4-semantics` onto
our current `18f-pages-staging` and found that there only be six commits
reflecting your changes.

The six commits are as follows:

```sh
648d93b wrap big footer h4 in li
 docs/_components/footers.md | 8 ++++----
 1 file changed, 4 insertions(+), 4 deletions(-)
42c1960 remove top margin from h4 in big footer
 src/stylesheets/components/_footer.scss | 4 ++++
 1 file changed, 4 insertions(+)
8373b72 fix footer primary link formatting
 src/stylesheets/components/_footer.scss | 11 ++++++-----
 1 file changed, 6 insertions(+), 5 deletions(-)
5c95c28 src: fix primary link spacing on desktop
 src/stylesheets/components/_footer.scss | 1 +
 1 file changed, 1 insertion(+)
d727a34 remove top margin from h4 in big footer
 src/stylesheets/components/_footer.scss | 2 +-
 1 file changed, 1 insertion(+), 1 deletion(-)
cb5ee11 fix footer primary link formatting
 src/stylesheets/components/_footer.scss | 2 +-
 1 file changed, 1 insertion(+), 1 deletion(-)
```

If you'd like to rebase your commits onto `18f-pages-staging` one more time, you
are more than welcome to. You need to be careful to discard any commits made to the
`docs/` and `dist/` generated files. These changes aren't related to other files
you may have changed in the `docs/` directory.

Here's a shell history of the commands I ran to clear those commits.

```sh
: 1464006881:0;git co madmanlear/footer-h4-semantics
: 1464006894:0;git co -b footer-h4-semantics
: 1464006915:0;git rebase origin/18f-pages-staging
: 1464006930:0;git rm -r --cached dist
: 1464006943:0;git rebase --skip
: 1464006967:0;git rm docs/assets/js/vendor/uswds.min.js
: 1464007072:0;rm -rvf dist
: 1464006981:0;git rebase --skip
: 1464007033:0;git add src/stylesheets/components/_footer.scss
: 1464007083:0;git rebase --skip
```

When rebasing your changes onto `18f-pages-staging` you will need to make sure
that any files or directories that are going to conflict such as the `dist/`
directory or the `docs/assets/js/vendor/uswds.min.js` file get deleted. Then,
during the `git rebase` you'll need to proceed by skipping those commits using
`git rebase --skip`.

I've pushed up another branch with your changes in this PR #1183. Feel welcome
to comment, add to via a PR, or rebase this PR with the instructions above.

Thanks for you contributions, @madmanlear! :tada:

**Comment by maya** [comment]
Closing in favor of #1183.

**Pull request closed without merging**
