### PR TITLE
[Medium footer]: Fix inconsistent text line breaks in IE 11

### PR DESCRIPTION
**Pull request by maya**
## Description

This fixes medium footer inconsistent text line breaks in IE 11. Removes the flexbox rule.

This is what it looks like:

screen shot 2016-06-10 at 9 29 12 pm

Fixes: #460.

### CODE REVIEW

**Comment by rogeruiz** [comment]
@maya Looks like this failed on the Screener test. I'm not sure how to best look into Screener, but I'll look at it locally as well.

**Comment by maya** [comment]
@rogeruiz yea, this needs design review first.

**Comment by maya** [comment]
@ericadeahl @bradnunnally could you check this one out based on the screenshots above (I think we're having screener technical difficulties ATM, so I'll just point you here).

**Comment by ericadeahl** [comment]
@maya Looks fine based on the screenshot 👍

**Comment by juliaelman** [comment]
LGTM

**Pull request merged**
