### PR TITLE
Visual Style download button placement

### PR DESCRIPTION
**Pull request by mollieru**
> remove from 'typography'
> add above to 'visual style guide' intro text
> add below to 'colors'

### CODE REVIEW

**Comment by maya** [comment]
@mollieru are al of your PRs related? Can you do this in a single PR?

**Comment by mollieru** [comment]
@maya I don't have access to the command line and haven't been able to figure out how to on the website. so sorry!!

**Comment by maya** [comment]
@mollieru can you then create an issue about what you're trying to do and then we can assess in triage and a dev can help.

**Comment by maya** [comment]
Will be done in another PR.

**Pull request closed without merging**
