### PR TITLE
[Headers]: Add headers docs

### PR DESCRIPTION
**Pull request by maya**
## Description

Adds documentation to headers component.

~~Please merge #1408 first.~~

https://standards-staging-add-headers-docs.apps.cloud.gov/headers/

Before you hit Submit, make sure you’ve done whichever of these applies to you:

- [x] Follow the [18F Front End Coding Style Guide](https://pages.18f.gov/frontend/) and [Accessibility Guide](https://pages.18f.gov/accessibility/checklist/).
- [x] Run `npm test` and make sure the tests for the files you have changed have passed.
- [x] Run your code through [HTML_CodeSniffer](http://squizlabs.github.io/HTML_CodeSniffer/) and make sure it’s error free.
- [x] Title your pull request using this format: [Website] - [UI component]: Brief statement describing what this pull request solves.

### CODE REVIEW

**Comment by juliaelman** [comment]
Can we add a `<code>` around the points in the docs that reference code? e.g. `role=banner`

**Comment by juliaelman** [comment]
@kategarklavs or @jameshupp might be good to get your 👀  on this one last time 👍

**Comment by maya** [comment]
@juliaelman sure can you let me know what lines need it?

**Comment by juliaelman** [comment]
@maya looks like you already made those fixes ^5!

**Comment by maya** [comment]
@juliaelman it was brought to my attention that @kategarklavs and @jameshupp are making updates to the documentation and they will be adding their updates here.

**Comment by juliaelman** [comment]
@maya cool - I'll wait to get the green light from those folks before merging in.

**Comment by kategarklavs** [comment]
@juliaelman Yes! That's correct — we'd written this header copy before @jameshupp and I finalized the format for all the other components. This should be done soon(!) (EOD, most likely)

**Comment by maya** [comment]
@kategarklavs's work has been incorporated from #1412. This is ready to review.

**Pull request closed without merging**
