### PR TITLE
Removed references to nonexistent _site directory.

### PR DESCRIPTION
**Pull request by alex**

### CODE REVIEW

**Comment by maya** [comment]
Thanks @alex!
 
The `_site` directory is jekyll related and appears when you bring the site down locally and run it. The reason we had this in our documentation like this was bc we compile our Sass to CSS using jekyll, but since we are manually taking a copy of `main.css` from `_site/assets/css` and putting it in `assets/css` it seems like we should change this so it's clearer and more consistent.

**Comment by alex** [comment]
@maya interesting, perhaps that section should indicate you need to run jekyl first?

**Comment by maya** [comment]
@alex I'm going to close this out for now in favor of opening issue #885.

**Comment by alex** [comment]
:+1:

**Pull request closed without merging**
