### PR TITLE
[Headers]: Fix code sample display

### PR DESCRIPTION
**Pull request by maya**
## Description

This fixes the code sample display by adding the partial code directly into the components as recommended by @rogeruiz. 

Previously, we had to show code sample html and the actual html for the partials depending on the use case or else it would render the partial inside the code sample. We tried doing this but were not able to get the indentation correctly displayed bc of how jekyll formats includes. It would reset all the indentation to the left for the partials.

Also, just noted some very strange display with the previous method on the headers page. This fix should resolve that. Although it would be very cool to use the mini-components that are consumed by bigger components, it's not possible at this point. 

- [x] Run `npm test` and make sure the tests for the files you have changed have passed.
- [x] Title your pull request using this format: [Website] - [UI component]: Brief statement describing what this pull request solves.

cc: @yozlet @juliaelman @msecret

### CODE REVIEW

**Comment by maya** [comment]
One question I have is: should we remove the partials (dropdown, mega menu, secondary nav) from the `src/html` directory?

Feel free to respond to this or emoji vote: 👍 or 👎

**Comment by juliaelman** [comment]
@maya I 👍  this at first because I _think_ I know where you are heading, but am not entirely clear what your thoughts are as an alternative. Can you explain your thoughts a bit more?

**Comment by maya** [comment]
@juliaelman sure, around what specifically?

**Comment by juliaelman** [comment]
@maya in regards to this question:

> One question I have is: should we remove the partials (dropdown, mega menu, secondary nav) from the src/html directory?

**Comment by maya** [comment]
@juliaelman @msecret partials deleted in 5bf151e. This is ready.

**Pull request merged**
