### PR TITLE
Fix aria hidden

### PR DESCRIPTION
**Pull request by joshbruce**
Remove from _base.scss: aria-hidden, display:none
Add class to _accordion.scss: usa-accordion-content-collapsed, display:none
Update accordion preview classes
Update accordion.js: Add remove class to expand and collapse.
Update styleguide.js to display code accordion collapsed on load.

### CODE REVIEW

**Comment by joshbruce** [comment]
Adding @ducklet - There you go, I think. If you look at the "replace lost functionality" commit - you should be able to see what was done with the JavaScript - jQuery makes it pretty simple when you know the functions and classes. :)

**Comment by joshbruce** [comment]
Fixes #1120

**Comment by ducklet** [comment]
@joshbruce looks good to me :) thank you!!

**Comment by msecret** [comment]
@joshbruce we just merged the somewhat large change to not check in the compiled `dist` files as well as not copying around files into the `docs` folder. This means this PR is merge conflicted, but the good news is there should be much less merge conflicts in the future.

When you rebase, none of the files in `dist` or `docs/assets` should be checked in. For more info check #1164.

**Comment by joshbruce** [comment]
@msecret - No worries. Will see what I can do. Maybe @ducklet can duplicate the changes and do a separate PR - as I think I will have to anyway as well (not sure what all is involved in a "rebase" and what it allows for).

I will add it to my backlog though.

**Comment by joshbruce** [comment]
@msecret - Don't merge this i fit integrates. I need to add the new class to the pages that use accordions. Just wanted to see quickly what would happen.

**Comment by joshbruce** [comment]
@msecret, @ducklet - Should be good to go. 

I could only find collapsed accordions on the Typography page that were not code samples generated from the JavaScript.

Good job to the 18f crew on isolating `/src` and the other directories, much easier to understand what needs to be changed.

**Comment by rogeruiz** [comment]
Hey @joshbruce, we're doing a little branch switcheroo and will need to close this since the branch names will change. We would still like to get these changes into `staging` once the branches are switched over. We will return to this work once the branch switch is complete.

**Comment by joshbruce** [comment]
@rogeruiz - No worries. Couple of questions:

1. What caused the decision to not merge the changes prior to the branch name changing? (Would like to know in case I end up in a similar situation in my own GitHub workflows.)
1. What action(s), if any, will be required on my part once it is done? (Assuming a PR into the new staging branch.)

**Comment by maya** [comment]
@joshbruce the branch switch is complete! Feel free to re-open.

>1. What caused the decision to not merge the changes prior to the branch name changing? (Would like to know in case I end up in a similar situation in my own GitHub workflows.)
I believe there were changes on the `dist` and scss on `docs` which we no longer use (35 file changes).

>2. What action(s), if any, will be required on my part once it is done? (Assuming a PR into the new staging branch.)
Cleaning up the above should be all that's needed.

**Pull request closed without merging**
