### PR TITLE
Fixes casing, adds link

### PR DESCRIPTION
**Pull request by nicoleslaw**
Minor capitalization corrections for [18F style](https://pages.18f.gov/content-guide/capitalization/)

### CODE REVIEW

**Comment by maya** [comment]
@nicoleslaw thanks so much for submitting this! I see the link added but not capitalization. What is supposed to be capitalized?

**Comment by nicoleslaw** [comment]
Sorry about that—should be fixed. (I did the PR on the web and I think it timed out without me realizing.)

**Comment by llolly** [comment]
إلغاء الإشتراك

‏في الجمعة، ١ يوليو، ٢٠١٦, Nicole Fenton <notifications@github.com> كتب:

> Sorry about that—should be fixed. (I did the PR on the web and I think it
> timed out without me realizing.)
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/18F/web-design-standards/pull/1297#issuecomment-230003411>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AKoR4dQrTSYwHMmT2Q75Tys9Xsda3rkhks5qRU3ugaJpZM4JDNA2>
> .
>


-- 
❤️llolly

**Comment by maya** [comment]
@nicoleslaw can you re-open this PR against our `staging` branch? That's where all of our development work happens and is the default branch in GitHub. 

Here are some notes on our use of branches: https://github.com/18F/web-design-standards#our-use-of-branches

Closing for now but can hopefully merge soon!

**Pull request closed without merging**
