### PR TITLE
add form template documentation

### PR DESCRIPTION
**Pull request by carodew**
Includes sign in form, password reset form, and address form
(Hope I'm doing this right).

### CODE REVIEW

**Comment by msecret** [comment]
@carodew it looks like some extra commits where tagged onto this one. Don't worry though, I think one of the devs should work with you to figure out the workflow.

**Comment by carodew** [comment]
@msecret Yah, I thought it looked strange. :/

**Comment by carodew** [comment]
Soooooo ... @maya recommended I take my edits and move them to a new PR. 

But it looks like this thing has gathered more commits in the meantime?

**Comment by carodew** [comment]
moved my form template documentation to a new branch: https://github.com/18F/web-design-standards/pull/520

**Comment by maya** [comment]
Superseded by #520.

**Pull request closed without merging**
