### PR TITLE
[WIP, DO NOT MERGE] testing changes to see why Federalist won't build - do not merge

### PR DESCRIPTION
**Pull request by wslack**

### CODE REVIEW

**Comment by wslack** [comment]
Do not merge; something weird happened with the version bump

**Comment by donjo** [comment]
@wslack do you need this open anymore or did you finish testing? re-open if necessary.

**Comment by wslack** [comment]
@donjo I didn't but did y'all solve the issue blocking builds?

**Comment by donjo** [comment]
@wslack yeah I'm not sure what exactly was going on but I restarted some builds and everything has been building fine going forward.

**Comment by wslack** [comment]
kk must have been NPM

**Pull request closed without merging**
