### PR TITLE
[Website, Label, Alerts, Links] Background color and text color mixin and classes

### LINKED ISSUE #968: Multiple colors for labels?
I apologize for not requesting this sooner, but I would love it if we could have multiple color choices for labels. I [defined my own in another project](https://github.com/18F/micropurchase/commit/8181b6fd6b8c7d473eaf3760992efa6c91c5ee9c) so we could color visually distinguish various types of auctions in a list, but I almost made some accessibility mistakes and it would be great if there were a good collection of colors with light/dark text as appropriate for better contrast. Thank you.

### LINKED ISSUE #1104: Styles in the documentation are not in the distributed file?  Why?
Hi US-WDS, I'm looking at the documentation here:

https://playbook.cio.gov/designstandards/visual-style/#text-accessibility

where it's recommended to use the listed color combinations, with css classes, etc., however they're not actually included in the {uswds.css}, they're only in {styleguide.css} therefore they can't be used in a real project w/o re-compiling the SCSS files.  This leads to a lot of confusion.

### LINKED ISSUE #1158: Background color mixins
**Description**

When applying background colors to elements, it would be nice if there was a simple way to also apply the proper text colors based on the text accessibility portion of the Standards. 

Mixins can facilitate this move and is in keeping with our use of [Bourbon](http://bourbon.io).

See PR #1129

**Ask**

@msecret, @maya, and @carodew, and I were discussing this in the aforementioned PR, which has been closed for further discussion by the community. 

The ask is described by the _To do_.

**To do**

Bringing over the ideas I saw mentioned from the PR - let me know if I missed something.
- [x] Determine the naming convention to be used. The PR used usa-bgcolor-*.
- [x] Determine how to handle `a` tags - should links be defined within the mixin - when a developer chooses a background-color they automatically get the `a` color; or, let the developer handle this?
- [x] Modify `/src` files to ensure proper incorporation.
  - [ ] Update alerts and label components to use mixin.

### LINKED ISSUE #1242: [Website, Label, Alerts, Links] Background color and text color mixin and classes
## Issue type
- Website
- Label
- Alerts
- Amendment to #1158 
- Groundwork for #1239 
## Description
1. The compiled CSS does not apply a color for text or links based on background color. 
2. Currently, for the "Visual style" page, we have helpers in applying background colors, as well as font colors using two separate class definitions (one for background and one for text color - see "Neutrals on colored backgrounds). Promoting these classes to a new `_colors.scss` file would allow defining font and link colors based on background color (note: transparent and white should use defaults), also allows developers to apply background colors without modifying or extending the compiled CSS. 
3. Making a `@mixin` within the `_utilities.scss` would also allow those extending the UI Components to apply background colors easily. We also don't have an example of links on a background other than white or transparent - some backgrounds could or would result in a reduction in contrast; reducing accessibility considerations.
## Steps to reproduce the issue
1. View `/docs/doc_assets/css/styleguide.scss` line 592 to see the background color helpers.
2. See #1239 to see how this could be leveraged on labels.
3. View "Alerts" page to see how it could be leveraged for the alerts component.
4. View "Buttons" to see how this might be used there as well - possibly not recommended because, semantically, interactive content (links) cannot be inside a `button`; therefore, use of the classes or `@mixin` would increase code bloat with no benefit.
## Other
- [ ] We don't have an example of `color-primary-alt-light` should we? If so, should it use base or white?
- [ ] We don't have an example of `color-secondary-light` should we? If so, should it use base or white?
- [ ] We don't have an example of `color-gray-lightest` should we? If so, should it use base or white?
- [ ] We don't have an example of `color-gray-warm-dark` should we? If so, should it use base or white?
- [ ] We don't have an example of `color-gray-cool-light` should we? If so, should it use base or white?
- [ ] We don't have an example of `color-cool-blue` should we? If so, should it use base or white?

### PR DESCRIPTION
**Pull request by joshbruce**
## Description

* Fixes #1158
* Fixes #1242
* Fixes #1104 
* Fixes #968
* Groundwork for #1239

* Adds definition for links on a “light” background color.
* Adds `background-color` to `/src/core/_utilities.scss` using Sass
conditionals instead of individual `@mixins` like #1129.
* Adds import of **new** `/src/stylesheets/core/_colors.scss` file.
* Deprecates most `.usa-color-*` classes in
`/docs/doc_assets/styleguide.scss` as they are promoted to a
`_colors.scss` (save `.usa-color-white`) - classes not removed from
`styleduide.scss` with this iteration of the PR as I am not sure where
they are used.

## Additional information

* This iteration is limited to effects on the “Visual style” page only.
Will await feedback on changes and desire before spreading out to other
areas of the Standards.
* This uses `color-gray-dark` for dark links on light backgrounds -
contrast of ~7.98:1. This choice was based on an assumption that light
backgrounds would mirror more the dark background solution (matching
the plain text color more) as opposed to the default link colors.
* The single `@mixin` allows for more detailed definition and
combinations (if we choose a different link text color, we can add a
conditional, which would automatically update results for those using
the classes or `@mixin`).
* It does not, at this point, address the desire to allow developers to
use the `@mixin` and set specific background and font colors; however,
in those cases, I believe the recommendation would be not to use the
`@mixin` or classes…just straight `background-color` CSS.

Tagging the parties from the previous PR: @maya, @msecret, @carodew

### CODE REVIEW

**Comment by joshbruce** [comment]
Hmmmmm...seems Screener caught the change I made to the "Visual style" page. Given the nature of Screener failures being thrown anytime there is a change to the rendered page, I'm curious about how the team handles failures in general.

Are the reasons for failure investigated further or trusted without further investigation?

I'm pretty sure I know the answer, but would like to check my assumptions.

**Comment by bradnunnally** [comment]
Hey @joshbruce. We are working on the workflow the team is going to be using for Screener since it's a new tool for us. Based on a conversation yesterday, we (the designers on the team) will be looking at screener if:

- Developer asks us to take a look based on a failure
- If a Pull Request has a design review associated with it
- If it's a formal release, a design review via screener will occur along with any of the development review that is part of a formal release.

@msecret & @ericadeahl - Did I miss anything? The above was based on the notes I took during out chat.

**Comment by maya** [comment]
@joshbruce thanks for submitting this pull request! This work is not on our current [product roadmap](https://github.com/18F/web-design-standards/wiki/Product-roadmap), so will not be able to be reviewed at this time. Feel free to use it on your own project and keep us posted on how it goes.

As a last note: keeping PRs smaller in scope: 1 issue per PR, gives a better chance that it will be reviewed.

**Comment by joshbruce** [comment]
@maya - Thanks. Will do.

**Comment by joshbruce** [comment]
@maya - Thought the status of the PR became closed the other day; so, not sure what, if anything I should do here. Maybe change the PR from "fixes" to just references - that way it's not a multiple issue PR? Or, would you like me to close this?

Just don't want to clutter up either the issues or PR spaces.

**Comment by maya** [comment]
@joshbruce thanks for checking in. Sure, I'll close for now and we can revisit it when we're able to get it on the roadmap. Thanks again!

**Pull request closed without merging**
