### PR TITLE
Remove Bourbon prefixing mixins

### PR DESCRIPTION
**Pull request by tysongach**
- These mixins are removed in Bourbon 5.0
- Autoprefixer will automatically add prefixes where needed

### CODE REVIEW

**Comment by rogeruiz** [comment]
Hey @tysongach! Thanks for this PR. This is great in helping use migrate to Bourbon 5.0 ( #994 ). I don't think we'll want to have any visual regressions due to removing the prefixes. [Specifically for IE9 and Safari iOS 8.4 which require the prefix](http://caniuse.com/#search=transform). Since we know have a gulp asset-pipeline, could you add Autoprefixer to this PR as well?

Here are two gulp plugins that you help [`gulp-autoprefixer`](https://github.com/sindresorhus/gulp-autoprefixer) and [`gulp-postcss` using the npm `autoprefixer` package](https://github.com/postcss/autoprefixer#gulp). Either one is fine for now as it will prevent CSS regressions in the targeted browsers I mentioned above. Let me know if you need any help getting them in the asset pipeline. You will need to make sure you add the transformations to the `defaultStream` and the `minifiedStream` [found here](https://github.com/18F/web-design-standards/blob/18f-pages-staging/config/gulp/sass.js#L50-L65).

Thanks again!

**Comment by tysongach** [comment]
@rogeruiz Ah, I assumed Autoprefixer was already in place! If it’s alright, I’ll leave this PR as is and your team can get `gulp-autoprefixer` set up in another PR, as I don’t have the bandwidth at the moment.

**Comment by rogeruiz** [comment]
Sounds good. Let's leave it open and we'll need you to rebase this later on
so we can merge it in. :+1:

if ( typos ) blame( fingers );
Roger Steve Ruiz ::: XFBB
202-600-1208

On Mar 15, 2016, at 2:54 PM, Tyson Gach <notifications@github.com> wrote:

@rogeruiz <https://github.com/rogeruiz> Ah, I assumed Autoprefixer was
already in place! If it’s alright, I’ll leave this PR as is and your team
can get gulp-autoprefixer set up in another PR, as I don’t have the
bandwidth at the moment.

—
You are receiving this because you were mentioned.
Reply to this email directly or view it on GitHub
<https://github.com/18F/web-design-standards/pull/1046#issuecomment-196971526>

**Comment by juliaelman** [comment]
@rogeruiz is this ready to be merged in?

**Comment by maya** [comment]
@juliaelman since this has changes to `src/stylesheets/components/_skipnav.scss` it looks like it needs to be added to `docs` and `dist`, unless we're finished removing `dist`.

**Comment by rogeruiz** [comment]
Closed by the work on #1176

**Pull request closed without merging**
