### PR TITLE
Background colors

### PR DESCRIPTION
**Pull request by joshbruce**
By using mixins we decouple dependence on styleguide.css helper
classes. Further, by making classes, designers and developers can
quickly generate accessible background and text color combinations.

See #933

Include @carodew

### CODE REVIEW

**Comment by maya** [comment]
Hi @joshbruce, that's a neat idea to tie the background and text color into a mixin. I think that the mixins help to enforce these standards, but reduce flexibility in trying different combinations out. To be clear, this PR does not include the "Colors on a white background" in the example - is that right?

**Comment by joshbruce** [comment]
Hey @maya - Thanks. You are correct - the main set for this PR used the non-white backgrounds found in: https://standards.usa.gov/visual-style/#text-accessibility

However, if we want, more can always be added and, I believe, the mixins would only increase the compiled size if used. If it would be beneficial I can add the white-backgrounds in another PR.

Regarding flexibility - there's a root mixin all the pre-defined mixins use:

@mixin bgcolor($background, $color)

This allows any background and text color combination and would be available for anyone including the utilities.scss to their sass builds. The root mixin also only sets background-color; so, background-image et al can still be applied. Only setting background, I believe, would cause issues.

**Comment by joshbruce** [comment]
ps. @maya - On further reflection - we *could* eliminate the other mixins in favor of *just* the bgcolor() one to reduce confusion and the number of mixins in _utilities.scss. Would need to modify the change done to the _alerts.scss for this PR.

**Comment by carodew** [comment]
As long as this doesn't change the actual color combinations that we recommend for text accessibility, I don't think this needs a separate visual design review. Personally I like the idea of using mixins to make the process easier but still allowing flexibility, although ultimately I defer to the dev team on that one.

**Comment by joshbruce** [comment]
@maya - I'm considering closing this and resubmitting - as I don't think I can do what I want to without doing so.

To increase flexibility even further we could define the root mixin as:

@mixin colors($text: $color-black, $background: transparent)

This work though not tested. This is a better function name semantically for what it does. This also allows us to create a default of transparent with black text. Further, we can set the font color without having a background color. Finally, the mixin maintains the core functionality and flexibility.

Thoughts?

ps. If you know a way for me to update this PR to make that change without having to close and submit anew - please let me know.

**Comment by msecret** [comment]
@joshbruce I think that slightly improves although I think what's here is also fine.

Could you restructure this code based on what we talked about in #1137 , moving the changes from `docs` to `src` and running the build process? Again, sorry for having you do that. We could potentially help out by forking off your fork if you're interested.

**Comment by maya** [comment]
@msecret `usa-bgcolor-*` doesn't comply with our coding styleguide. What do you think would work better?

**Comment by joshbruce** [comment]
@msecret - I think I will want to do a different PR for this one anyway. So, yes, can definitely start switching over to modifying the `/src`.

This PR, as it stands, does not consider the `a` tag, which I believe we would want to. Might be worth reaching out to @carodew again to see if this affects design considerations. Especially since this could apply to links within alerts and the label component.

@maya - That's fair. I will wait to do anything further on this score until hearing back regarding what to name the mixins and if @carodew has anything to add re links.

Sorry I might have jumped the gun on the PR part of this - appreciate the methodical and reflective approach in its consideration.

Would like to leave it open, for now, if possible. Or, convert to an issue. Whichever helps y'all the most with your workflow.

**Comment by msecret** [comment]
@joshbruce it would actually help us a lot to close PRs that aren't being actively worked on because we're working though the large amount of PRs currently submitted.

**Comment by joshbruce** [comment]
@msecret - Know how that goes. Not a problem.

See #1158 

Closing.

**Pull request closed without merging**
