### PR TITLE
[Website] Update incorrect documentation on variables

### PR DESCRIPTION
**Pull request by msecret**
## Description

The documentation on this is now incorrect as variables.scss is no longer being imported so is not technically where these things are defined.

## Additional information

Also, the way this was previously worded, it sounded like it was suggesting people to modify the src files of the standards which I've been working hard to stop from happening because it's a terrible practice.

Before you hit Submit, make sure you’ve done whichever of these applies to you:

- [x] Follow the [18F Front End Coding Style Guide](https://pages.18f.gov/frontend/) and [Accessibility Guide](https://pages.18f.gov/accessibility/checklist/).
- [x] Run `npm test` and make sure the tests for the files you have changed have passed.
- [x] Run your code through [HTML_CodeSniffer](http://squizlabs.github.io/HTML_CodeSniffer/) and make sure it’s error free.
- [x] Title your pull request using this format: [Website] - [UI component]: Brief statement describing what this pull request solves.

### CODE REVIEW

**Comment by maya** [comment]
This looks good, the only issue I have is the "importing it before uswds in Sass" bit. I think it could be rewritten a bit. Maybe say: 

>add your custom `variables.scss` import before the Draft Standards `all` import in your `main.scss` file.

Possibly addresses #1334 although I wonder if we need to add a section in https://standards.usa.gov/getting-started/developers/

**Comment by kategarklavs** [comment]
@maya This looks good to me. Also, I'm happy to chat more about adding a new section to the Getting Started section, if you think that this is necessary.

**Comment by maya** [comment]
@kategarklavs cool, and just checking "changing variable values and importing it **before uswds in Sass.**" sounds OK to you?

**Comment by kategarklavs** [comment]
@maya Hello again, and apologies for not being clear before — that sounds good to me 👍

**Pull request merged**
