### PR TITLE
Attempt to fix mega menu

### PR DESCRIPTION
**Pull request by msecret**
## Description

Include a high-level description of the issue your pull request fixes; include only one issue per pull request. Please also link to the GitHub issue it resolves.

## Additional information

Include any of the following (as necessary): 

* Relevant research and support documents
* Type of content review needed: stylistic or copy editing
* Screenshot images
* Notes

Before you hit Submit, make sure you’ve done whichever of these applies to you:

- [ ] Follow the [18F Front End Coding Style Guide](https://pages.18f.gov/frontend/) and [Accessibility Guide](https://pages.18f.gov/accessibility/checklist/).
- [ ] Run `npm test` and make sure the tests for the files you have changed have passed.
- [ ] Run your code through [HTML_CodeSniffer](http://squizlabs.github.io/HTML_CodeSniffer/) and make sure it’s error free.
- [ ] Title your pull request using this format: [Website] - [UI component]: Brief statement describing what this pull request solves.

### CODE REVIEW

**Comment by donjo** [comment]
Still seeing the issue here with this fix. Any other ideas on what may have changed in the release?

**Comment by msecret** [comment]
Are you seeing the docs site issue or the fractal site issue? They're probably separate.

**Comment by donjo** [comment]
On the fractal site. I saw your mention of that on Slack but just repeating it here for historical record.

**Comment by donjo** [comment]
Ok, I pushed some changes up to @msecret's branch and this should be working now.

**Comment by maya** [comment]
Glad that it's showing up now in desktop view.

I see this in mobile view:
screen shot 2017-10-03 at 3 46 14 pm


Quick visual design check, the header now does not extend to the width of the page like before. I checked @rtwell's designs in https://github.com/18F/web-design-standards/issues/2086  and it seems to be page width too. Was this change intended or decided somewhere else? 

### Current

screen shot 2017-10-03 at 3 41 35 pm

### Design via https://github.com/18F/web-design-standards/issues/2086 

screen shot 2017-10-03 at 3 42 21 pm

/cc @thisisdano

**Comment by maya** [comment]
### Basic mega menu:
screen shot 2017-10-03 at 3 52 51 pm

### Designs:
29525591-c8f5d2ce-8658-11e7-8710-dedca4c2265a

**Comment by donjo** [comment]
@maya to answer the first question, the change to the megamenu width was deliberate and I confirmed with @msecret and @rtwell. Sorry for not giving you all the info you needed to QA on that.

Second, I'm not seeing the problems you're seeing with the mobile nav. Maybe things are being cached? I was having problems with that yesterday but a hard refresh fixed it. The screenshots did, however, let me know that the spacing was off between the top item in the list and the submenu list items so I pushed up a fix for that.

**Comment by donjo** [comment]
closing this out since the work has moved to #2161

**Pull request closed without merging**
