### PR TITLE
Modify title for 'Forgot username'

### PR DESCRIPTION
**Pull request by burgwyn**
Updating title entry to align with field name

### CODE REVIEW

**Comment by maya** [comment]
@burgwyn, thanks for opening this PR. Are you able to resolve the merge conflicts?

**Comment by burgwyn** [comment]
I've checked in the merge conflicts.  Let me know if it needs any cleanup.

**Comment by maya** [comment]
@burgwyn it still says there are merge conflicts. It's kind of hard to differentiate what changes were made currently, bc it shows 33 files changed, when I think you meant to change one line of code? If you could open a PR with just that 1 line changed, that would be best.

**Comment by burgwyn** [comment]
Closing pull request and creating another

**Pull request closed without merging**
