### PR TITLE
[Website]: Visual style page accordions

### LINKED ISSUE #1245: [ Website ]: Not all accordions work without JavaScript
## Issue type
* Website

## Description

Not all the accordions on the site work without JavaScript, #1224 covers the accordion page, but the Typography page doesn't open. And I'm assuming that there may be other pages where accordion's are collapsed by default.

## Steps to reproduce the issue

1. Turn off JavaScript
1. Navigation to https://wds-microsite-release.apps.cloud.gov/visual-style/#pairings
1. Click the expand button on the accordion
1. Witness the blatant refusal for the accordion to open sans JS

## Additional information [optional]

* Taking a look at the changes in #1224 #1225 
*  `aria-expanded="false"` can be removed from any accordions we'd like open by default
* open the top accordion with  `aria-expanded="true"`

### PR DESCRIPTION
**Pull request by joshbruce**
## Description

Fixes #1245

## Additional information

* The fix from #1224 asks that all accordions on a page start as
expanded either by omitting `aria-hidden` or by setting it to `false`.
* The accordions on pages beyond the “Accordions” and “Visual style”
pages are for “Documentation” blocks, which are expanded by default.
* This PR removes `aria-hidden` from all accordion content blocks,
demonstrating the application of the #1224 fix. Modifications to other
pages should not be necessary beyond that required by the clean and
semantic milestone.

### CODE REVIEW

**Comment by joshbruce** [comment]
Note: Since I'm working this PR and #1244, I can just as easily add this change to that one...depending on how much deliberation is needed for #1244. 

Further, after marinating on it a bit, my concerns about possible merge conflicts (see #1245) should not be a problem given the areas of each file that are being modified by this and #1244.

**Comment by rogeruiz** [comment]
@joshbruce This touches on the `typography` page. Are there other pages that need the `aria-hidden` attribute updated?

**Comment by joshbruce** [comment]
@rogeruiz - I did some analysis at one point - thought it was on #1245 to be honest (can't find the issue for some reason and not sure why I didn't reference it here - sorry) - maybe @shawnbot remembers. 

The findings, after looking at each rendered page individually, were:

1. All "documentation" accordions are expanded by default and do not need the attribute applied. However, for the sake of refactoring, it could be removed.
2. All the "code" examples are generated through JS; therefore, don't display if scripts are turned off - not affected by this solution.
3. The only page with accordions generated from markup appear on the "Visual style" page.

So, while accordions are used on every page - they are unaffected by the accepted solution for the site as it was at the time of PR submission.

**Comment by joshbruce** [comment]
@rogeruiz - That was killing me - I was thinking of the ID conversation from #1225. Having said, the assessment from the previous comment still holds and is, essentially, an expanded version of the note in the second bullet of the PR description.

**Comment by rogeruiz** [comment]
Hey @joshbruce. Looks like you'll need to rebase this branch onto the latest work on `staging`. 18F/web-design-standards#1261 has removed `screener` and that will get this PR to pass in `CircleCI`. If it's helpful, I can rebase these changes manually and submit a new pull request with that update. Thanks!

**Comment by joshbruce** [comment]
@rogeruiz - Rebased. Tests running now.

**Comment by rogeruiz** [comment]
Thanks @joshbruce 🎉

**Pull request merged**
