### PR TITLE
add release zip file

### PR DESCRIPTION
**Pull request by alexose**
Rebuilt the release zip now that politespace.scss is gone

@maya

### CODE REVIEW

**Comment by maya** [comment]
You just used the latest assets folder right? bc we had other changes

**Comment by alexose** [comment]
er, didn't mean to.  let's try this again.

**Comment by maya** [comment]
@alexose confirmed that this was built from scratch, and not just removing politespace.scss. It includes other changes.

**Comment by maya** [comment]
Looks good :+1:  Let's do this thing.

**Pull request merged**
