### PR TITLE
Vertical line space in accordions

### PR DESCRIPTION
**Pull request by msecret**
The line space in accordions was broken because every nested last-child
was having it's margins removed, which it requires. This ensures only
the first child last child does.

Fixes https://github.com/18F/web-design-standards/issues/445

### CODE REVIEW

**Comment by maya** [comment]
@msecret will we run into any issues with nested first-child elements for this same reason?

**Comment by msecret** [comment]
@maya I didn't do it because I wanted to keep the amount of code changed to as minimal as possible to lessen the chance that I could create more regressions. Although it would make sense to have that rule.

**Comment by maya** [comment]
@msecret can you add it in just to be consistent? I can't think of a regression we could get from doing this.

**Comment by maya** [comment]
lgtm

**Pull request merged**
