### PR TITLE
[Maintenance] Complete the switch from Travis CI to Circle CI

### PR DESCRIPTION
**Pull request by juliaelman**
**This pull request is downstream from #1195** 

## Description

This pull request includes the switch from using Travis CI to Circle CI. Here are some of the things that are accomplished in these changes:

- Removal of unused `go` file and references
- Removal of `.travis.yml`file and references
- Updating `CONTRIBUTING.md` 
- Adds `manifest-staging.yml` to create specific config references to our staging instance
- Adds running of unit tests against pull requests 🎉 
- Adds Circle CI badge to `README.md`

The Travis CI webhook has also been removed as of submission of this pull request.

### CODE REVIEW

**Comment by juliaelman** [comment]
@rogeruiz @yozlet would be great to have y'alls 👀  on this pull request! We might be able to compress some things to shorten the time for the CI to run (2:50 minutes), but am thinking it might be good to merge this in for now and we work on shortening that time in future PR.

Just a reminder that this is downstream from #1195

**Comment by rogeruiz** [comment]
🚀 🎸 looks good. I'll let @yozlet weigh in, but I ran this locally and everything went smooth.

**Comment by yozlet** [comment]
Looks great! :shipit: once the upstream PR is merged.

**Comment by yozlet** [comment]
@juliaelman Is that `.18f-pages.yml` file unused because Pages doesn't need it, or because we're not publishing to Pages any more? If the latter, is removal of the file going to unpublish the site from Pages? If so, we may want to hold off until we have the new `18f-pages` branches in place with the redirects.

**Comment by juliaelman** [comment]
@yozlet thanks for the inquiry! This will not remove us publishing to 18F pages, as that is determined by what branches we have in place in the repo. See the docs for 18F pages for more info.

AFAIK, this file was only in place to create the `/designstandards` route as the `baseurl` for the standards website. Assuming was because the original url was `playbook.cio.gov/designstandards/`. Going to revert this back for now, as I have a feeling like this *might* cause issues with our redirects.

**Comment by yozlet** [comment]
#1195 is now merged, so merging this too! Thanks @juliaelman!

**Pull request merged**
