### PR TITLE
Override default `baseurl:` with /designstandards

### PR DESCRIPTION
**Pull request by mbland**
cc: @mollieru @maya

### CODE REVIEW

**Comment by maya** [comment]
Did we change the URL we plan to use from `/design` to `/designstandards`? @mbland @mollieru

**Comment by mbland** [comment]
Sorry, yes, that was suggested in an offline email thread.

**Comment by mbland** [comment]
Ping... It appears https://playbook.cio.gov/designstandards is ready and waiting... :smiley:

**Comment by maya** [comment]
@mbland your PR includes an older version of config.yml which still has:

`# 18F pages base url config`
`baseurl: /usfwds`

`url: https://pages.18f.gov/usfwds`

which has since been removed.

Can you update to use the latest one. Currently it goes to `http://127.0.0.1:4000/usfwds/` locally.

**Comment by mbland** [comment]
@maya  That's updated in your `18f-pages-staging` branch; when you merge that into `18-pages`, the `_config.yml` file will receive those updates. If we make those changes in this branch, it'll likely cause conflicts when the merge takes place. This `_config_18f_pages.yml` file is brand new, and won't cause a conflict.

**Comment by mbland** [comment]
After chatting with @maya, going to close this PR and open a new one to merge into `18f-pages-staging`.

**Pull request closed without merging**
