### PR TITLE
Update Source Sans Pro fonts

### PR DESCRIPTION
**Pull request by miguelsousa**
This is to address issue #802.

The collective size of the new files is 546KB, while the previous version was 595KB. On the surface, this doesn't seem that big of a size reduction, but the new fonts actually support for more characters (which addresses issue #756, I believe), and they also support true small caps and old style numbers.

I did not generate new SVG files because those "fonts" are only needed for [**very old** browsers](http://caniuse.com/#feat=svg-fonts). I think they should be removed from this project. [WOFF](http://caniuse.com/#feat=woff), and soon [WOFF2](http://caniuse.com/#feat=woff2), are more broadly supported and have a smaller footprint.

### CODE REVIEW

**Comment by maya** [comment]
This is awesome - thanks so much @miguelsousa!

I think we can probably create a new issue about removing SVG fonts.

This will also resolve #737.

**Comment by maya** [comment]
@miguelsousa Quick question: What are old style numbers?

What do you recomend as the best place to view all available characters, glyphs, etc for Source Sans Pro?

**Comment by jpyuda** [comment]
Old-style numbers have ascenders and descenders much like lowercase letters. They were traditionally used in running copy, while using lining numerals for tables. (when you want all the numbers to line up)

http://theworldsgreatestbook.com/wp-content/uploads/2011/11/figureStyles1.gif illustrates it well.

**Comment by miguelsousa** [comment]
@maya 
> I think we can probably create a new issue about removing SVG fonts.

I can take care of that, if you want.

> What do you recomend as the best place to view all available characters, glyphs, etc

[This PDF](https://github.com/miguelsousa/source-sans-pro-subset/blob/master/sourcesanspro-regular-webfont.pdf) is probably the best place. Keep in mind that this is showing the subsetted fonts that were submitted in the PR and not the original fonts. The original fonts have a lot more glyphs and support a lot more languages. If you come across characters that are not supported by the current subsetted fonts, let me know and I'll generate new subset fonts with broader support.

I will also try to remember to update the fonts here by submitting a PR whenever a new version of [Source Sans Pro](https://github.com/adobe-fonts/source-sans-pro/releases) comes out. I've created a [dedicated repository](https://github.com/miguelsousa/source-sans-pro-subset) to make that easy and reproducible.

**Pull request merged**
