### PR TITLE
Content fix to intro paragraph

### PR DESCRIPTION
**Pull request by mollieru**
Address grammar + run on in intro paragraph of 2nd section

### CODE REVIEW

**Comment by mollieru** [comment]
@awfrancisco good catch, thanks! @maya g2g.

**Comment by mollieru** [comment]
@maya fixed the 508 language. all good?

**Comment by maya** [comment]
@mollieru See: https://github.com/18F/web-design-standards/issues/689#issuecomment-143040165

**Comment by maya** [comment]
Oh I see you did break it up into two sentences.

**Comment by maya** [comment]
@mollieru sorry, can we do one more update.... "this resource follows industry-standard web accessibility guidelines". Thanks!

**Comment by maya** [comment]
@kategarklavs says.. "I might replace ​_It serves as a guide ..._​ with ​_It provides a guide for creating_​, and replace ​_beautiful and easy-to-use_​ with ​_beautiful, easy-to-use_​"

@mollieru

**Comment by maya** [comment]
@kategarklavs also recommends changing wording from American people to the public" bc the content guide encourages use of "public," when possible: https://pages.18f.gov/content-guide/conscious-style/

@mollieru

**Comment by mollieru** [comment]
@kategarklavs is it ok if we stick w the 'American people' in this sense because a) this might not only be used for the 'public' and b) gets a lil more at the feel of human-centered-ness (as in we're building tools for *people*)

**Comment by kategarklavs** [comment]
@mollieru That sounds good to me (and I like the connection between _people_ + _human-centered design_).

**Pull request merged**
