### PR TITLE
Sass Shuffle

### PR DESCRIPTION
**Pull request by tysongach**
This PR re-structure the Sass importing and moves a few partials around to make things a bit more clear.

What we get in the end is every `@import` in `all.scss` can be alphabetized by separating non-rendering Sass (`core/`) from rendering Sass/CSS.

Changes:

- Rename `utilities` partial to `mixins`
- Create utility classes section
  - Create a `utilities/` directory to house all utility classes
  - Move the `.usa-sr-only` class into the `utilities/` directory
  - Use the `sr-only` mixin to build the `.usa-sr-only` utility class so to stop
    duplicating those declarations
- Move `base` partial into `elements` directory
  - This partial is styling base HTML elements, which is what the elements
  directory is for
- Move grid partial into utilities
- ABC imports
  - Now that the `core/` directory is all non-rendering Sass, we can ABC every
    Sass import in `all.scss` because we've built expectations and a system for
    source order.

Ref: https://robots.thoughtbot.com/separate-rendering-sass-from-non-rendering-sass

### CODE REVIEW

**Comment by rogeruiz** [comment]
Hey @tysongach! Thanks for this PR. This looks good to me. :tada: :+1:

**Comment by maya** [comment]
Looks good to me too. Looping in @msecret.

**Comment by rogeruiz** [comment]
Hmm, sorry about this, @tysongach. I can help you debug this. @msecret, I took a further look and I'm seeing some visual regressions comparing your branch to `18f-pages`.

screen shot 2016-03-15 at 2 58 47 pm
screen shot 2016-03-15 at 2 58 51 pm

**Comment by tysongach** [comment]
@rogeruiz Oh, bummer! That’s no good.

I just took a gander…it looks like those grid classes (`.usa-width-one-whole`, `.usa-width-one-half`, etc. coming from `utilities/_grid.scss`) are not making it into the final CSS output final (`http://localhost:4000/assets/css/styleguide.css`). Is this also the case when you run locally?

This led me to `docs/assets/css/styleguide.scss` and Line 6, which is `@import 'uswds';`. I’m not sure I see where this import traces back to?

I _think_ it’s supposed to be importing `docs/_scss/_uswds.scss`, yeah? Does Jekyll line this path up for us?

**Comment by rogeruiz** [comment]
@tysongach Ah Jekyll does not, but the gulp automation _should_. How are you running the server, try using `npm start` after rebasing what's on `18f-pages-staging`.

**Comment by maya** [comment]
@rogeruiz do `utilities` need to be added to gulp since it's a new folder?

**Comment by tysongach** [comment]
@rogeruiz I was running `gulp website:serve`. I rebased and got the same results with `npm start`.

Also, when I made these changes and fired up the server, I got a really messy `HEAD`:

```
Changes not staged for commit:
  (use "git add/rm <file>..." to update what will be committed)
  (use "git checkout -- <file>..." to discard changes in working directory)

  modified:   dist/css/uswds.css
  modified:   dist/css/uswds.min.css
  modified:   dist/css/uswds.min.css.map
  modified:   dist/js/uswds.js
  modified:   dist/js/uswds.min.js
  modified:   dist/js/uswds.min.js.map
  modified:   docs/_scss/_uswds.scss
  deleted:    docs/_scss/core/_base.scss
  modified:   docs/_scss/core/_defaults.scss
  deleted:    docs/_scss/core/_grid.scss
  deleted:    docs/_scss/core/_utilities.scss
  modified:   docs/_scss/core/_variables.scss
  modified:   docs/_scss/lib/_neat.scss
  modified:   docs/assets/js/vendor/uswds.min.js

Untracked files:
  (use "git add <file>..." to include in what will be committed)

  docs/_scss/core/_mixins.scss
  docs/_scss/elements/_base.scss
  docs/_scss/utilities/
```

I guess I’m confused why so many things changed, and also what should and should not be committed?

**Comment by rogeruiz** [comment]
Ah yes. This is due to a refactor in the way we deploy the `/docs` site. We'll need to add some documentation on how to commit changes to `/docs`, `/dist`, and `/src`. :thought_balloon:

**Comment by msecret** [comment]
@rogeruiz what's the state of the regression you found?

**Comment by rogeruiz** [comment]
@maya From what I can see, gulp is successfully copying the files over

```
▾ docs/
  ...
  ▾ _scss/
    ▸ components/
    ▸ core/
    ▸ elements/
    ▸ lib/
    ▾ utilities/
        _grid.scss
        _usa-sr-only.scss
      .DS_Store
      _uswds.scss
```

**Comment by rogeruiz** [comment]
@msecret It seems like the ordering of the `_grid.scss` file is the culprit.

```
@import 'utilities/grid';
@import 'core/mixins';
```

The regression goes away when `_grid.scss` is pulled in _before_ `_mixins.scss`.

**Comment by tysongach** [comment]
@rogeruiz Ohhh! That’s interesting. Maybe this is the issue:

So, Neat comes with a [built-in `media()` mixin](http://thoughtbot.github.io/neat-docs/latest/#media) and it looks like we are also defining _another_ mixin [here within the repo](https://github.com/18F/web-design-standards/blob/18f-pages-staging/src/stylesheets/core/_utilities.scss#L2) **of the same name**.

We should probably remove one, if they are serving the same purpose, or namespace the one defined here within the repo.

**Comment by maya** [comment]
@tysongach when I remove our `media` include, I get an npm build error. If they do the same thing shouldn't Bourbon's work the same?

**Comment by rogeruiz** [comment]
@tysongach Great catch on two `media` mixins. I'm seeing that we're only using 
it for the `grid.scss` and then using our custom `media` mixin for `uswds` 
specific styles. For now, I think prefixing ours with `uswds-` would be the best
way to make sure we're not clobbering the `media` mixin in Bourbon.


I think we can either merge this in or I can create a new PR with your changes 
and mine and we close this one. Let me know. You can apply the patch file I'm 
attaching using the following command, once you unzip the `uswds-media.patch`
file:


```sh
git apply uswds-media.patch
```

[uswds-media.patch.zip](https://github.com/18F/web-design-standards/files/180336/uswds-media.patch.zip)

Here's a _long_ diff of where we need to change it. 

```diff
diff --git a/src/stylesheets/components/_alerts.scss b/src/stylesheets/components/_alerts.scss
index cb390ce..4663419 100644
--- a/src/stylesheets/components/_alerts.scss
+++ b/src/stylesheets/components/_alerts.scss
@@ -6,7 +6,7 @@
   margin-top: 1.5em;
   padding: 1em;
 
-  @include media($medium-screen) {
+  @include uswds-media($medium-screen) {
     background-size: 5.2rem;
   }
 
@@ -26,7 +26,7 @@
   padding-left: 3.5rem;
   vertical-align: top;
 
-  @include media($medium-screen) {
+  @include uswds-media($medium-screen) {
     padding-left: 5rem;
   }
 }
@@ -34,8 +34,8 @@
 .usa-alert-heading {
   margin-bottom: .3rem;
   margin-top: 0;
-  
-  @include media($medium-screen) {
+
+  @include uswds-media($medium-screen) {
     margin-top: .3rem;
   }
 }
diff --git a/src/stylesheets/components/_disclaimer.scss b/src/stylesheets/components/_disclaimer.scss
index f5cc6d4..b0ddf5b 100644
--- a/src/stylesheets/components/_disclaimer.scss
+++ b/src/stylesheets/components/_disclaimer.scss
@@ -4,7 +4,7 @@
   padding-bottom: .5rem;
   padding-top: .5rem;
 
-  @include media($small-screen) {
+  @include uswds-media($small-screen) {
     font-size: $h5-font-size;
   }
 }
@@ -15,7 +15,7 @@
   display: none;
   float: right;
 
-  @include media($large-screen) {
+  @include uswds-media($large-screen) {
     display: block;
   }
 }
diff --git a/src/stylesheets/components/_footer.scss b/src/stylesheets/components/_footer.scss
index 07700dc..71ea7b0 100644
--- a/src/stylesheets/components/_footer.scss
+++ b/src/stylesheets/components/_footer.scss
@@ -11,7 +11,7 @@
     padding-bottom: 2rem;
     padding-top: 2rem;
 
-    @include media($medium-screen) {
+    @include uswds-media($medium-screen) {
       border-top: none;
     }
   }
@@ -33,7 +33,7 @@
     padding-left: 2.5rem;
     padding-right: 2.5rem;
 
-    @include media($medium-screen) {
+    @include uswds-media($medium-screen) {
       padding-left: 0;
       padding-right: 0;
     }
@@ -41,14 +41,14 @@
     li {
       margin-left: 1rem;
 
-      @include media($medium-screen) {
+      @include uswds-media($medium-screen) {
         margin-left: 0;
       }
     } 
   }
 
   .usa-grid-full {
-    @include media($medium-screen) {
+    @include uswds-media($medium-screen) {
       padding-left: 2.5rem;
       padding-right: 2.5rem;
     }
@@ -58,15 +58,15 @@
 .usa-footer-medium {
   .usa-footer-primary-section {
     padding: 0;
-    
-    @include media($medium-screen) {
+
+    @include uswds-media($medium-screen) {
       padding-bottom: 1rem;
       padding-top: 1rem;
     }
   }
 
   .usa-footer-nav ul {
-    @include media($medium-screen) {
+    @include uswds-media($medium-screen) {
       align-items: center;
       display: flex;  
     }
@@ -80,8 +80,8 @@
 
   .usa-footer-primary-section {
     padding-bottom: 2rem;
-    
-    @include media($medium-screen) {
+
+    @include uswds-media($medium-screen) {
       padding-bottom: 1rem;
       padding-top: 1rem;
 
@@ -98,14 +98,14 @@ li.usa-footer-primary-content,
 li.usa-footer-primary-content {
   border-top: 1px solid $color-base;      
 
-  @include media($medium-screen) {
+  @include uswds-media($medium-screen) {
     border: none;
   }
 
   &:last-child {
     border-bottom: 1px solid $color-base;
 
-    @include media($medium-screen) {
+    @include uswds-media($medium-screen) {
       border-bottom: none;
     }
   }
@@ -116,7 +116,7 @@ li.usa-footer-primary-content {
   padding-left: 2.5rem;
   padding-right: 2.5rem;
 
-  @include media($medium-screen) {
+  @include uswds-media($medium-screen) {
     float: right;
     padding: 0;
   }
@@ -147,20 +147,20 @@ li.usa-footer-primary-content {
 }
 
 .usa-footer-big-secondary-section {
-  @include media($medium-screen) {
+  @include uswds-media($medium-screen) {
     padding-top: 5rem;
   }  
 }
 
 .usa-footer-contact-links {
-  @include media($medium-screen) {
+  @include uswds-media($medium-screen) {
     text-align: right;
   }
 }
 
 .usa-footer-big {
   .usa-footer-primary-section {
-    @include media($medium-screen) {
+    @include uswds-media($medium-screen) {
       padding-bottom: 4rem;
       padding-top: 3rem;
     }
@@ -169,14 +169,14 @@ li.usa-footer-primary-content {
   ul {
     padding-bottom: 2.5rem;
 
-    @include media($medium-screen) {
+    @include uswds-media($medium-screen) {
       padding-bottom: 0;
     }
     
     &:last-child {
       border-bottom: 1px solid $color-base;
 
-      @include media($medium-screen) {
+      @include uswds-media($medium-screen) {
         border-bottom: none;
       }
     }
@@ -193,7 +193,7 @@ li.usa-footer-primary-content {
       background-size: 1.3rem;
       padding-left: 3.5rem;
 
-      @include media($medium-screen) {
+      @include uswds-media($medium-screen) {
         background: none;
         padding-bottom: 0;
         padding-left: 0;
@@ -209,7 +209,7 @@ li.usa-footer-primary-content {
         cursor: pointer;
         margin: 0;
 
-        @include media($medium-screen) {
+        @include uswds-media($medium-screen) {
           background: none;
           padding-left: 0;
         }        
@@ -226,7 +226,7 @@ li.usa-footer-primary-content {
 }
 
 .usa-sign_up-header {
-  @include media($medium-screen) {
+  @include uswds-media($medium-screen) {
     margin: 0;
     padding: 2rem 0;
   }
@@ -247,9 +247,9 @@ li.usa-footer-primary-content {
 
 .usa-footer-contact-heading {
   margin-top: 0;
-  
-  @include media($medium-screen) {
-    margin-top: 1rem;  
+
+  @include uswds-media($medium-screen) {
+    margin-top: 1rem;
   }
 }
 
@@ -257,7 +257,7 @@ li.usa-footer-primary-content {
   display: block;
   padding-top: 1rem;
 
-  @include media($medium-screen) {
+  @include uswds-media($medium-screen) {
     display: inline-block;
     padding-left: 1em;
   }
diff --git a/src/stylesheets/components/_forms.scss b/src/stylesheets/components/_forms.scss
index 2998822..c137119 100644
--- a/src/stylesheets/components/_forms.scss
+++ b/src/stylesheets/components/_forms.scss
@@ -1,7 +1,7 @@
 $usa-form-width: 32rem;
 
 form {
-  @include media($medium-screen) {
+  @include uswds-media($medium-screen) {
     max-width: $usa-form-width;
   }
 
@@ -15,7 +15,7 @@ form {
     margin-bottom: 1.5em;
     margin-top: 2.5rem;
 
-    @include media($medium-screen) {
+    @include uswds-media($medium-screen) {
       padding-left: 2.7em;
       padding-right: 2.7em;
       width: auto;
@@ -45,37 +45,37 @@ fieldset {
 }
 
 .usa-form-large {
-  @include media($medium-screen) {
+  @include uswds-media($medium-screen) {
     max-width: 46rem;
   }
 }
 
 input.usa-input-tiny {
-  @include media($medium-screen) {
+  @include uswds-media($medium-screen) {
     max-width: 6rem;
   }
 }
 
 input.usa-input-medium {
-  @include media($medium-screen) {
+  @include uswds-media($medium-screen) {
     max-width: 12rem;
   }
 }
 
 .usa-input-grid {
-  @include media($medium-screen) {
+  @include uswds-media($medium-screen) {
     padding-right: 5%;
   }
 }
 
 .usa-input-grid:last-of-type {
-  @include media($medium-screen) {
+  @include uswds-media($medium-screen) {
     padding-right: 0;
   }
 }
 
 .usa-input-grid-small {
-  @include media($medium-screen) {
+  @include uswds-media($medium-screen) {
     float: left;
     width: 35%;
   }
@@ -90,7 +90,7 @@ input.usa-input-medium {
 }
 
 .usa-input-grid-medium {
-  @include media($medium-screen) {
+  @include uswds-media($medium-screen) {
     float: left;
     width: 65%;
   }
@@ -105,7 +105,7 @@ input.usa-input-medium {
 }
 
 .usa-input-grid-large {
-  @include media($medium-screen) {
+  @include uswds-media($medium-screen) {
     float: left;
     width: 100%;
   }
diff --git a/src/stylesheets/components/_search.scss b/src/stylesheets/components/_search.scss
index 33cebac..5a14331 100644
--- a/src/stylesheets/components/_search.scss
+++ b/src/stylesheets/components/_search.scss
@@ -27,7 +27,7 @@ $usa-btn-big-width:     11.6rem;
     padding-top: 0;
     width: calc(100% - #{$usa-btn-small-width});
 
-    @include media($small-screen) {
+    @include uswds-media($small-screen) {
       width: calc(100% - #{$usa-btn-medium-width});
     }
   }
@@ -42,7 +42,7 @@ $usa-btn-big-width:     11.6rem;
     padding: 0;
     width: $usa-btn-small-width;
 
-    @include media($small-screen) {
+    @include uswds-media($small-screen) {
       background-image: none;
       width: $usa-btn-medium-width;
     }
@@ -51,13 +51,13 @@ $usa-btn-big-width:     11.6rem;
   .usa-search-submit-text {
     display: none;
 
-    @include media($small-screen) {
+    @include uswds-media($small-screen) {
       display: block;
     }
   }
 
   &.usa-search-big {
-    @include media($small-screen) {
+    @include uswds-media($small-screen) {
       $height: 4.4rem;
       $width: $usa-btn-big-width;
 
@@ -77,7 +77,7 @@ $usa-btn-big-width:     11.6rem;
   }
 
   &.usa-search-small {
-    @include media($small-screen) {
+    @include uswds-media($small-screen) {
       $width: $usa-btn-small-width;
 
       [type="search"],
diff --git a/src/stylesheets/core/_mixins.scss b/src/stylesheets/core/_mixins.scss
index e8e07e0..0b6d897 100644
--- a/src/stylesheets/core/_mixins.scss
+++ b/src/stylesheets/core/_mixins.scss
@@ -1,5 +1,5 @@
 // Mobile-first media query helper
-@mixin media($bp) {
+@mixin uswds-media($bp) {
   @media screen and (min-width: #{$bp}) {
     @content;
   }
diff --git a/src/stylesheets/elements/_buttons.scss b/src/stylesheets/elements/_buttons.scss
index 54d9dfe..e277d31 100644
--- a/src/stylesheets/elements/_buttons.scss
+++ b/src/stylesheets/elements/_buttons.scss
@@ -34,7 +34,7 @@ button,
   width: 100%;
   -webkit-font-smoothing: antialiased;
 
-  @include media($small-screen) {
+  @include uswds-media($small-screen) {
     width: auto;
   }
 
diff --git a/src/stylesheets/elements/_typography.scss b/src/stylesheets/elements/_typography.scss
index 2b7118b..11deda3 100644
--- a/src/stylesheets/elements/_typography.scss
+++ b/src/stylesheets/elements/_typography.scss
@@ -153,11 +153,11 @@ p,
   @include h3();
   margin-bottom: 0;
 
-  @include media($small-screen) {
+  @include uswds-media($small-screen) {
     @include h1();
   }
 
-  @include media($medium-screen) {
+  @include uswds-media($medium-screen) {
     @include title();
   }
 }

```

**Comment by tysongach** [comment]
@rogeruiz Thanks! Just applied the patch and rebased; should be all set now.

**Comment by msecret** [comment]
@rogeruiz I actually see no reason as to why we should use our own, we should only use the bourbon/neat `media` mixin. I'm guessing to switch we have to change what grid-settings variables we pass to it?

**Comment by tysongach** [comment]
@rogeruiz I agree, they are _very_ similar and the Neat mixin could solve the same needs the internal mixin has. That being said, I’d suggest refactoring that in another Issue/PR. Thoughts?

**Comment by rogeruiz** [comment]
@msecret Let's comment our thoughts on this in #994. I agree with @tysongach about merging this in. With this PR landed, we're one of sum closer to leveraging Bourbon more. :+1:

**Comment by maya** [comment]
I'd like to know what it looks like to use Bourbon's media mixin and remove ours and would prefer that (I think) over prefixing ours.

**Comment by maya** [comment]
Blocked until we resolve the `@include media` issue.

**Comment by rogeruiz** [comment]
Closing this ticket for now so we can switch over branches easily. Once we have a solution for the `@include media` issue, we can reopen this PR.

**Pull request closed without merging**
