### PR TITLE
Select component: Pixel-fit arrow-both.svg

### PR DESCRIPTION
**Pull request by sawyerh**
This is super picky 😅 but makes the icon look less blurry, especially on retina screens.

image

### CODE REVIEW

**Comment by maya** [comment]
@sawyerh not picky at all! I'm working on a related issue here #2178 and uploaded a 2x png. Does that resolve it or does it need more work?

**Comment by maya** [comment]
Ah, just realized you shared an SVG, not a PNG. Wonder how it compares to the new SVG I uploaded: https://github.com/18F/web-design-standards/pull/2178/files#diff-c92e431a8d1091d484058af08dee8196

**Comment by sawyerh** [comment]
@maya ah I missed that one. It looks like the SVG in #2178 is still a little misaligned with the pixel grid:

image

**Comment by maya** [comment]
Got it, I pulled in your code to my PR too: https://github.com/18F/web-design-standards/pull/2178/files#diff-c92e431a8d1091d484058af08dee8196

**Pull request merged**
