### PR TITLE
Fix styleguide again

### PR DESCRIPTION
**Pull request by msecret**
Fixed merge conflict from here: 

https://github.com/18F/web-design-standards/pull/985

There are additional changes here to the dist files because in #1049 we didn't commit any changes to the compiled files.

@nickjs, you can either merge this PR in, or take this branch, merge it into your forked branch and merge that PR.

### CODE REVIEW

**Comment by nickjs** [comment]
@msecret Sorry so does this branch include everything from #985 just rebased onto the refactor?

**Comment by msecret** [comment]
Yes @nickjs, it should. 

Unfortunately, it now needs to be rebased again. I'll try and take a look at some point.

**Comment by juliaelman** [comment]
Moving to the backlog for now until it is rebased.

**Comment by rogeruiz** [comment]
Closing this PR in favor of #1180 which will `cherry-pick` these commits.

**Pull request closed without merging**
